import "/src/css/layout.css";
import "./themeSwitch";
import { listenersToHome } from "./eventListener/homeListener";
import { listenersToTodo } from "./eventListener/todoListener";
import { listenersToProject } from "./eventListener/projectListener";
import { dom } from "./dom";
dom.displayAllProjects();
listenersToHome();
listenersToTodo();
listenersToProject();
